<?php

namespace Ionic\Push\Models;

class MessageError extends \SplEnum {
    const INVALID = "INVALID";
    const UNKNOWN = "UNKNOWN";
    const UNABLE_TO_AUTH = "UNABLE_TO_AUTH";
    const NO_CREDENTIAL = "NO_CREDENTIAL";
    const INVALID_MESSAGE_FORMAT = "INVALID_MESSAGE_FORMAT";
    const ILLEGAL_CREDENTIAL_FORMAT = "ILLEGAL_CREDENTIAL_FORMAT";
    const INVALID_CREDENTIAL_PASSWORD = "INVALID_CREDENTIAL_PASSWORD";
    const NO_VALID_TOKENS = "NO_VALID_TOKENS";
    const INVALID_TOKEN = "INVALID_TOKEN";
    const APNS_BAD_TOPIC = "APNS_BAD_TOPIC";
    const APNS_TOPIC_DISALLOWED = "APNS_TOPIC_DISALLOWED";
    const APNS_BAD_DEVICE_TOKEN = "APNS_BAD_DEVICE_TOKEN";
    const APNS_DEVICE_TOKEN_NOT_FOR_TOPIC = "APNS_DEVICE_TOKEN_NOT_FOR_TOPIC";
    const APNS_UNREGISTERED = "APNS_UNREGISTERED";
    const APNS_BAD_CERTIFICATE_ENVIRONMENT = "APNS_BAD_CERTIFICATE_ENVIRONMENT";
    const APNS_BAD_CERTIFICATE = "APNS_BAD_CERTIFICATE";
    const GCM_INVALID_AUTH = "GCM_INVALID_AUTH";
    const GCM_ERROR = "GCM_ERROR";
    const GCM_INVALID_REGISTRATION = "GCM_INVALID_REGISTRATION";
    const GCM_INVALID_PACKAGE = "GCM_INVALID_PACKAGE";
    const GCM_MISMATCH_SENDER = "GCM_MISMATCH_SENDER";
    const GCM_TOO_BIG = "GCM_TOO_BIG";
    const GCM_INVALID_KEY = "GCM_INVALID_KEY";
    const GCM_INVALID_TTL = "GCM_INVALID_TTL";
    const GCM_UNKNOWN = "GCM_UNKNOWN";
}